name: Build OpenWrt with OpenSync

on:
  push:
    branches: [ develop ]

jobs:
  build-ea8300:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_BUILD_TOKEN }}
        submodules: true
    - name: Build Image for EA8300
      env:
          GH_BUILD_USERNAME: ${{ secrets.GH_BUILD_USERNAME }}
          GH_BUILD_PASSWORD: ${{ secrets.GH_BUILD_PASSWORD }}
      run: |
        make TARGET=IPQ40XX
        TAG=$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)
        TAR_NAME="ea8300-$TAG.tar.gz"
        tar cfz "$TAR_NAME" -C openwrt/bin/targets/ipq40xx/generic .
        curl -u "$GH_BUILD_USERNAME":"$GH_BUILD_PASSWORD" -T "$TAR_NAME" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/"$TAR_NAME""

  build-ecw5410:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_BUILD_TOKEN }}
        submodules: true
    - name: Build Image for ECW5410
      env:
          GH_BUILD_USERNAME: ${{ secrets.GH_BUILD_USERNAME }}
          GH_BUILD_PASSWORD: ${{ secrets.GH_BUILD_PASSWORD }}
      run: |
        make TARGET=ECW5410
        TAG=$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)
        TAR_NAME="ecw5410-$TAG.tar.gz"
        tar cfz "$TAR_NAME" -C openwrt/bin/targets/ipq806x/generic .
        curl -u "$GH_BUILD_USERNAME":"$GH_BUILD_PASSWORD" -T "$TAR_NAME" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/"$TAR_NAME""

  build-ap2220:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_BUILD_TOKEN }}
        submodules: true
    - name: Build Image for AP2220
      env:
          GH_BUILD_USERNAME: ${{ secrets.GH_BUILD_USERNAME }}
          GH_BUILD_PASSWORD: ${{ secrets.GH_BUILD_PASSWORD }}
      run: |
        make TARGET=AP2220
        TAG=$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)
        TAR_NAME="ap2220-$TAG.tar.gz"
        tar cfz "$TAR_NAME" -C openwrt/bin/targets/ipq40xx/generic .
        curl -u "$GH_BUILD_USERNAME":"$GH_BUILD_PASSWORD" -T "$TAR_NAME" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/"$TAR_NAME""
