name: Build OpenWrt with OpenSync

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_BUILD_TOKEN }}
        submodules: true
    - name: Build Image for IPQ40XX
      env:
          GH_BUILD_USERNAME: ${{ secrets.GH_BUILD_USERNAME }}
          GH_BUILD_PASSWORD: ${{ secrets.GH_BUILD_PASSWORD }}
      run: |
        make TARGET=IPQ40XX SDK_URL=https://downloads.openwrt.org/releases/19.07.2/targets/ipq40xx/generic/openwrt-sdk-19.07.2-ipq40xx-generic_gcc-7.5.0_musl_eabi.Linux-x86_64.tar.xz PROFILE=linksys_ea8300 IMAGE_URL=https://downloads.openwrt.org/releases/19.07.2/targets/ipq40xx/generic/openwrt-imagebuilder-19.07.2-ipq40xx-generic.Linux-x86_64.tar.xz
        TAG=$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)
        TAR_NAME="ea8300-$TAG.tar.gz"
        cp example/out/*.ipk build/workdir/bin/targets/ipq40xx/generic/
        tar cfz "$TAR_NAME" -C build/workdir/bin/targets/ipq40xx/generic .
        curl -u "$GH_BUILD_USERNAME":"$GH_BUILD_PASSWORD" -T "$TAR_NAME" "https://tip.jfrog.io/artifactory/tip-wlan-ap-firmware/"$TAR_NAME""
